import React from 'react';
import { View, StyleSheet, Alert, SafeAreaView } from 'react-native';
import { createDrawerNavigator, DrawerContentScrollView, DrawerItemList, DrawerItem } from '@react-navigation/drawer';
import { Settings, Home, LogOut, IndianRupee, TrendingUp } from 'lucide-react-native';
import { theme } from './theme';

import AdminTabs from './AdminTabs'; 
import AdminSettingsScreen from './AdminSettingsScreen';
import AdminGameRatesScreen from './AdminGameRatesScreen';
// --- ADDED: Import your new fund requests screen ---
import AdminFundRequestsScreen from './AdminFundRequestsScreen'; 

const Drawer = createDrawerNavigator();

// 1. CREATE THE CUSTOM DRAWER COMPONENT
function CustomDrawerContent(props) {
  const { onLogout } = props;

  const handleLogoutPress = () => {
    Alert.alert(
      "Secure Logout",
      "Are you sure you want to log out of the Admin Portal?",
      [
        { text: "Cancel", style: "cancel" },
        { 
          text: "Logout", 
          style: "destructive", 
          onPress: onLogout 
        }
      ]
    );
  };

  return (
    <SafeAreaView style={{ flex: 1 }} edges={['top', 'bottom']}>
      <DrawerContentScrollView {...props}>
        <DrawerItemList {...props} />
      </DrawerContentScrollView>

      <View style={styles.logoutSection}>
        <DrawerItem
          label="Secure Logout"
          icon={({ size }) => <LogOut color={theme.colors.danger} size={size} />}
          labelStyle={styles.logoutText}
          onPress={handleLogoutPress}
          style={styles.logoutItem}
        />
      </View>
    </SafeAreaView>
  );
}

// 2. MAIN DRAWER NAVIGATOR
export default function AdminDrawer({ adminData, onLogout }) {
  return (
    <Drawer.Navigator 
      drawerContent={(props) => <CustomDrawerContent {...props} onLogout={onLogout} />}
      screenOptions={{
        headerShown: false, 
        drawerActiveBackgroundColor: theme.colors.primaryLight,
        drawerActiveTintColor: theme.colors.primary,
        drawerInactiveTintColor: theme.colors.textDark,
      }}
    >
      <Drawer.Screen 
        name="AdminHome" 
        options={{ 
          drawerLabel: 'Home',
          drawerIcon: ({ color, size }) => <Home color={color} size={size} />
        }} 
      >
        {(props) => <AdminTabs {...props} adminData={adminData} />}
      </Drawer.Screen>

      {/* --- ADDED: Fund Requests Screen Screen --- */}
      <Drawer.Screen 
        name="FundRequests" 
        component={AdminFundRequestsScreen} 
        options={{ 
          drawerLabel: 'Fund Requests',
          drawerIcon: ({ color, size }) => <IndianRupee color={color} size={size} />,
          headerShown: true, // You can turn this on if you want a top nav bar with a burger menu toggle button automatically generated by React Navigation
          title: "Fund Requests"
        }} 
      />
      
      <Drawer.Screen 
        name="GlobalSettings" 
        component={AdminSettingsScreen} 
        options={{ 
          drawerLabel: 'App Settings',
          drawerIcon: ({ color, size }) => <Settings color={color} size={size} />
        }} 
      />

      <Drawer.Screen 
        name="GameRates" 
        component={AdminGameRatesScreen} 
        options={{ 
          drawerLabel: 'Game Rates',
          drawerIcon: ({ color, size }) => <TrendingUp color={color} size={size} />
        }} 
      />
    </Drawer.Navigator>
  );
}

// 3. STYLES FOR THE LOGOUT BUTTON
const styles = StyleSheet.create({
  logoutSection: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    paddingBottom: 20, 
    paddingTop: 10,
  },
  logoutText: {
    color: theme.colors.danger,
    fontWeight: '700',
    fontSize: 16,
    marginLeft: 0,
  },
  logoutItem: {
    backgroundColor: '#FEF2F2', 
    borderRadius: 24, 
    marginHorizontal: 10, 
    paddingLeft: 8, 
  }
});